version: "3.9"

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app/SintromCare/client
      - /app/SintromCare/client/node_modules
    command: ["npm", "run", "dev"]
    networks:
      - sintromcare-network

  module:
    build:
      context: ./module
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./module:/app/SintromCare/module
      - /app/SintromCare/module/node_modules
    command: ["npm", "start"]
    networks:
      - sintromcare-network

networks:
  sintromcare-network:
    driver: bridge
